version: "3.7"

services:

  server:
    container_name: book_server
    build:
      context: ./
    restart: always
    ports:
      - "8080:8080" # webapp
    volumes:
      - ${PWD}/logs:/logs/book
